services:
  - type: web
    name: titanic-agent-api
    env: python
    region: singapore
    plan: free
    rootDir: backend
    runtime: python
    pythonVersion: "3.12.0"
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
      - key: TEMPERATURE
        value: "0"
      - key: AGENT_MAX_ITERATIONS
        value: "5"
      - key: AGENT_VERBOSE
        value: "false"
      - key: ALLOWED_ORIGINS
        value: "*"
